## Encode all columns with Ordinal Values (train)
- this notebook goes First 


In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import scale
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression  
from sklearn.metrics import mean_squared_error

In [2]:
ames_train = pd.read_csv('./datasets/train.csv')
ames_test = pd.read_csv('./datasets/test.csv')
ames_train

Id        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0      109  533352170           60        RL           NaN     13517   Pave   
1      544  531379050           60        RL          43.0     11492   Pave   
2      153  535304180           20        RL          68.0      7922   Pave   
3      318  916386060           60        RL          73.0      9802   Pave   
4      255  906425045           50        RL          82.0     14235   Pave   
...    ...        ...          ...       ...           ...       ...    ...   
2046  1587  921126030           20        RL          79.0     11449   Pave   
2047   785  905377130           30        RL           NaN     12342   Pave   
2048   916  909253010           50        RL          57.0      7558   Pave   
2049   639  535179160           20        RL          80.0     10400   Pave   
2050    10  527162130           60        RL          60.0      7500   Pave   

     Alley Lot Shape Land Contour  ... Screen Porch Pool Area Pool QC Fence  \
0      NaN       IR1          Lvl  ...            0         0     NaN   NaN   
1      NaN       IR1          Lvl  ...            0         0     NaN   NaN   
2      NaN       Reg          Lvl  ...            0         0     NaN   NaN   
3      NaN       Reg          Lvl  ...            0         0     NaN   NaN   
4      NaN       IR1          Lvl  ...            0         0     NaN   NaN   
...    ...       ...          ...  ...          ...       ...     ...   ...   
2046   NaN       IR1          HLS  ...            0         0     NaN   NaN   
2047   NaN       IR1          Lvl  ...            0         0     NaN   NaN   
2048   NaN       Reg          Bnk  ...            0         0     NaN   NaN   
2049   NaN       Reg          Lvl  ...            0         0     NaN   NaN   
2050   NaN       Reg          Lvl  ...            0         0     NaN   NaN   

     Misc Feature Misc Val Mo Sold Yr Sold  Sale Type  SalePrice  
0             NaN        0       3    2010        WD      130500  
1             NaN        0       4    2009        WD      220000  
2             NaN        0       1    2010        WD      109000  
3             NaN        0       4    2010        WD      174000  
4             NaN        0       3    2010        WD      138500  
...           ...      ...     ...     ...        ...        ...  
2046          NaN        0       1    2008        WD      298751  
2047          NaN        0       3    2009        WD       82500  
2048          NaN        0       3    2009        WD      177000  
2049          NaN        0      11    2009        WD      144000  
2050          NaN        0       6    2010        WD      189000  

[2051 rows x 81 columns]

In [3]:
ames_test

Id        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0    2658  902301120          190        RM          69.0      9142   Pave   
1    2718  905108090           90        RL           NaN      9662   Pave   
2    2414  528218130           60        RL          58.0     17104   Pave   
3    1989  902207150           30        RM          60.0      8520   Pave   
4     625  535105100           20        RL           NaN      9500   Pave   
..    ...        ...          ...       ...           ...       ...    ...   
873  1662  527377110           60        RL          80.0      8000   Pave   
874  1234  535126140           60        RL          90.0     14670   Pave   
875  1373  904100040           20        RL          55.0      8250   Pave   
876  1672  527425140           20        RL          60.0      9000   Pave   
877  1939  535327160           20        RL          70.0      8400   Pave   

    Alley Lot Shape Land Contour  ... 3Ssn Porch Screen Porch Pool Area  \
0    Grvl       Reg          Lvl  ...          0            0         0   
1     NaN       IR1          Lvl  ...          0            0         0   
2     NaN       IR1          Lvl  ...          0            0         0   
3     NaN       Reg          Lvl  ...          0            0         0   
4     NaN       IR1          Lvl  ...          0          185         0   
..    ...       ...          ...  ...        ...          ...       ...   
873   NaN       Reg          Lvl  ...          0            0         0   
874   NaN       Reg          Lvl  ...          0            0         0   
875   NaN       Reg          Lvl  ...          0            0         0   
876   NaN       Reg          Lvl  ...          0            0         0   
877   NaN       Reg          Lvl  ...          0            0         0   

    Pool QC  Fence Misc Feature Misc Val Mo Sold  Yr Sold  Sale Type  
0       NaN    NaN          NaN        0       4     2006        WD   
1       NaN    NaN          NaN        0       8     2006        WD   
2       NaN    NaN          NaN        0       9     2006        New  
3       NaN    NaN          NaN        0       7     2007        WD   
4       NaN    NaN          NaN        0       7     2009        WD   
..      ...    ...          ...      ...     ...      ...        ...  
873     NaN    NaN          NaN        0      11     2007        WD   
874     NaN  MnPrv          NaN        0       8     2008        WD   
875     NaN    NaN          NaN        0       8     2008        WD   
876     NaN   GdWo          NaN        0       5     2007        WD   
877     NaN   GdWo          NaN        0       3     2007        WD   

[878 rows x 80 columns]

In [4]:
# Create dataframe with all columns that have ordinal values 
ordinals_train = pd.DataFrame(ames_train, columns=['Lot Shape', 'Utilities', 'Land Slope', 'Overall Qual',
                                                     'Overall Cond', 'Exter Cond', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure', 
                                                     'BsmtFin Type 1', 'BsmtFinType 2', 'Heating QC', 'Electrical',
                                                     'Kitchen Qual', 'Functional', 'Fireplace Qu', 'Garage Finish', 'Garage Qual', 
                                                     'Garage Cond', 'Paved Drive', 'Pool QC', 'Fence'])

In [5]:
ordinals_test = pd.DataFrame(ames_test, columns=['Lot Shape', 'Utilities', 'Land Slope', 'Overall Qual',
                                                     'Overall Cond', 'Exter Cond', 'Bsmt Qual', 'Bsmt Cond', 'Bsmt Exposure', 
                                                     'BsmtFin Type 1', 'BsmtFinType 2', 'Heating QC', 'Electrical',
                                                     'Kitchen Qual', 'Functional', 'Fireplace Qu', 'Garage Finish', 'Garage Qual', 
                                                     'Garage Cond', 'Paved Drive', 'Pool QC', 'Fence'])

In [6]:
# check for nulls 
ordinals_train.isnull().sum()

Lot Shape            0
Utilities            0
Land Slope           0
Overall Qual         0
Overall Cond         0
Exter Cond           0
Bsmt Qual           55
Bsmt Cond           55
Bsmt Exposure       58
BsmtFin Type 1      55
BsmtFinType 2     2051
Heating QC           0
Electrical           0
Kitchen Qual         0
Functional           0
Fireplace Qu      1000
Garage Finish      114
Garage Qual        114
Garage Cond        114
Paved Drive          0
Pool QC           2042
Fence             1651
dtype: int64

In [7]:
ordinals_test.isnull().sum()

Lot Shape           0
Utilities           0
Land Slope          0
Overall Qual        0
Overall Cond        0
Exter Cond          0
Bsmt Qual          25
Bsmt Cond          25
Bsmt Exposure      25
BsmtFin Type 1     25
BsmtFinType 2     878
Heating QC          0
Electrical          1
Kitchen Qual        0
Functional          0
Fireplace Qu      422
Garage Finish      45
Garage Qual        45
Garage Cond        45
Paved Drive         0
Pool QC           874
Fence             706
dtype: int64

In [8]:
# replace null values with 'None' unless it does not make sense 

ordinals_train['Bsmt Cond'].fillna('None', inplace=True)
ordinals_train['Bsmt Qual'].fillna('None', inplace=True)
ordinals_train['Bsmt Exposure'].fillna('None', inplace=True)
ordinals_train['BsmtFin Type 1'].fillna('None', inplace=True)
ordinals_train['Fireplace Qu'].fillna('None', inplace=True)
ordinals_train['Garage Finish'].fillna('None', inplace=True)
ordinals_train['Garage Qual'].fillna('None', inplace=True)
ordinals_train['Garage Cond'].fillna('None', inplace=True)
ordinals_train['Fence'].fillna('None', inplace=True)

ordinals_test['Bsmt Cond'].fillna('None', inplace=True)
ordinals_test['Bsmt Qual'].fillna('None', inplace=True)
ordinals_test['Bsmt Exposure'].fillna('None', inplace=True)
ordinals_test['BsmtFin Type 1'].fillna('None', inplace=True)
ordinals_test['Fireplace Qu'].fillna('None', inplace=True)
ordinals_test['Garage Finish'].fillna('None', inplace=True)
ordinals_test['Garage Qual'].fillna('None', inplace=True)
ordinals_test['Garage Cond'].fillna('None', inplace=True)
ordinals_test['Fence'].fillna('None', inplace=True)
ordinals_test['Electrical'].fillna('None', inplace=True)




In [9]:
# drop these columns because they have two many null values, and probably won't affect the price of a house 
ordinals_train.drop(columns='BsmtFinType 2', inplace=True)
ordinals_train.drop(columns='Pool QC', inplace=True)

ordinals_test.drop(columns='BsmtFinType 2', inplace=True)
ordinals_test.drop(columns='Pool QC', inplace=True)

In [10]:
ordinals_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 878 entries, 0 to 877
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Lot Shape       878 non-null    object
 1   Utilities       878 non-null    object
 2   Land Slope      878 non-null    object
 3   Overall Qual    878 non-null    int64 
 4   Overall Cond    878 non-null    int64 
 5   Exter Cond      878 non-null    object
 6   Bsmt Qual       878 non-null    object
 7   Bsmt Cond       878 non-null    object
 8   Bsmt Exposure   878 non-null    object
 9   BsmtFin Type 1  878 non-null    object
 10  Heating QC      878 non-null    object
 11  Electrical      878 non-null    object
 12  Kitchen Qual    878 non-null    object
 13  Functional      878 non-null    object
 14  Fireplace Qu    878 non-null    object
 15  Garage Finish   878 non-null    object
 16  Garage Qual     878 non-null    object
 17  Garage Cond     878 non-null    object
 18  Paved Driv

In [11]:
ordinals_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 878 entries, 0 to 877
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Lot Shape       878 non-null    object
 1   Utilities       878 non-null    object
 2   Land Slope      878 non-null    object
 3   Overall Qual    878 non-null    int64 
 4   Overall Cond    878 non-null    int64 
 5   Exter Cond      878 non-null    object
 6   Bsmt Qual       878 non-null    object
 7   Bsmt Cond       878 non-null    object
 8   Bsmt Exposure   878 non-null    object
 9   BsmtFin Type 1  878 non-null    object
 10  Heating QC      878 non-null    object
 11  Electrical      878 non-null    object
 12  Kitchen Qual    878 non-null    object
 13  Functional      878 non-null    object
 14  Fireplace Qu    878 non-null    object
 15  Garage Finish   878 non-null    object
 16  Garage Qual     878 non-null    object
 17  Garage Cond     878 non-null    object
 18  Paved Driv

In [12]:
ordinals_test.isnull().sum()

Lot Shape         0
Utilities         0
Land Slope        0
Overall Qual      0
Overall Cond      0
Exter Cond        0
Bsmt Qual         0
Bsmt Cond         0
Bsmt Exposure     0
BsmtFin Type 1    0
Heating QC        0
Electrical        0
Kitchen Qual      0
Functional        0
Fireplace Qu      0
Garage Finish     0
Garage Qual       0
Garage Cond       0
Paved Drive       0
Fence             0
dtype: int64

In [13]:
ordinals_train.isnull().sum()

Lot Shape         0
Utilities         0
Land Slope        0
Overall Qual      0
Overall Cond      0
Exter Cond        0
Bsmt Qual         0
Bsmt Cond         0
Bsmt Exposure     0
BsmtFin Type 1    0
Heating QC        0
Electrical        0
Kitchen Qual      0
Functional        0
Fireplace Qu      0
Garage Finish     0
Garage Qual       0
Garage Cond       0
Paved Drive       0
Fence             0
dtype: int64

## Encode!! 

    -only columns of interest 
    

In [14]:
# encode all ordinal values on a scale from 1 to n values 
ordinals_train['Bsmt Cond'] = ordinals_train['Bsmt Cond'].replace({"None": 1, "Po": 2, 'Fa':3,'TA':4,'Gd':5,'Ex':6})
ordinals_train['Bsmt Cond']

0       4
1       4
2       4
3       4
4       5
       ..
2046    4
2047    4
2048    4
2049    4
2050    4
Name: Bsmt Cond, Length: 2051, dtype: int64

In [15]:
ordinals_test['Bsmt Cond'] = ordinals_test['Bsmt Cond'].replace({"None": 1, "Po": 2, 'Fa':3,'TA':4,'Gd':5,'Ex':6})
ordinals_test['Bsmt Cond']

0      4
1      4
2      5
3      4
4      4
      ..
873    4
874    4
875    4
876    4
877    4
Name: Bsmt Cond, Length: 878, dtype: int64

In [16]:
ordinals_train['Lot Shape'] = ordinals_train['Lot Shape'].replace({"IR1": 1, 'IR2':2,'IR3':3,'Reg':4})
ordinals_train['Lot Shape'].unique()

array([1, 4, 2, 3], dtype=int64)

In [17]:
ordinals_test['Lot Shape'] = ordinals_test['Lot Shape'].replace({"IR1": 1, 'IR2':2,'IR3':3,'Reg':4})
ordinals_test['Lot Shape'].unique()

array([4, 1, 3, 2], dtype=int64)

In [18]:
ordinals_train['Utilities'] = ordinals_train['Utilities'].replace({'NoSeWa':1,'NoSewr':2,'AllPub':3})
ordinals_train['Utilities'].unique()

array([3, 1, 2], dtype=int64)

In [19]:
ordinals_test['Utilities'] = ordinals_test['Utilities'].replace({'NoSeWa':1,'NoSewr':2,'AllPub':3})
ordinals_test['Utilities'].unique()

array([3, 2], dtype=int64)

In [20]:
ordinals_train['Exter Cond'] = ordinals_train['Exter Cond'].replace({'Po':1,'Fa':2,'TA':3, 'Gd':4,'Ex':5})
ordinals_train['Exter Cond'].unique()

array([3, 4, 2, 5, 1], dtype=int64)

In [21]:
ordinals_test['Exter Cond'] = ordinals_test['Exter Cond'].replace({'Po':1,'Fa':2,'TA':3, 'Gd':4,'Ex':5})
ordinals_test['Exter Cond'].unique()

array([2, 3, 4, 5, 1], dtype=int64)

In [22]:
ordinals_train['Bsmt Qual'] = ordinals_train['Bsmt Qual'].replace({'None':1, 'Po':2,'Fa':3,'TA':4, 'Gd':5,'Ex':6})
ordinals_train['Bsmt Qual'].unique()

array([4, 5, 3, 1, 6, 2], dtype=int64)

In [23]:
ordinals_test['Bsmt Qual'] = ordinals_test['Bsmt Qual'].replace({'None':1, 'Po':2,'Fa':3,'TA':4, 'Gd':5,'Ex':6})
ordinals_test['Bsmt Qual'].unique()

array([3, 5, 4, 6, 1, 2], dtype=int64)

In [24]:
ordinals_train['Heating QC'] = ordinals_train['Heating QC'].replace({'Po':1,'Fa':2,'TA':3, 'Gd':4,'Ex':5})
ordinals_train['Heating QC'].unique()

array([5, 3, 4, 2, 1], dtype=int64)

In [25]:
ordinals_test['Heating QC'] = ordinals_test['Heating QC'].replace({'Po':1,'Fa':2,'TA':3, 'Gd':4,'Ex':5})
ordinals_test['Heating QC'].unique()

array([4, 3, 5, 2], dtype=int64)

In [26]:
ordinals_train['Electrical'] = ordinals_train['Electrical'].replace({'Mix':1,'FuseP':2,'FuseA':3, 'FuseF':4,'SBrkr':5})
ordinals_train['Electrical'].unique()

array([5, 4, 3, 2, 1], dtype=int64)

In [27]:
ordinals_test['Electrical'] = ordinals_test['Electrical'].replace({'None':1,'FuseP':2,'FuseA':3, 'FuseF':4,'SBrkr':5})
ordinals_test['Electrical'].unique()

array([2, 5, 3, 4, 1], dtype=int64)

In [28]:
ordinals_train['Kitchen Qual'] = ordinals_train['Kitchen Qual'].replace({'Fa':1,'TA':2, 'Gd':3, 'Ex':4})
ordinals_train['Kitchen Qual'].unique()

array([3, 2, 1, 4], dtype=int64)

In [29]:
ordinals_test['Kitchen Qual'] = ordinals_test['Kitchen Qual'].replace({'Po': 1, 'Fa':2,'TA':3, 'Gd':4, 'Ex':5})
ordinals_test['Kitchen Qual'].unique()

array([2, 3, 4, 5, 1], dtype=int64)

In [30]:
ordinals_train['Functional'] = ordinals_train['Functional'].replace({'Sal':1,'Sev':2, 'Maj2':3, 'Maj1':4, 'Mod':5, 'Min2':6, 'Min1':7, 'Typ':8})
ordinals_train['Functional'].unique()

array([8, 5, 6, 4, 7, 2, 1, 3], dtype=int64)

In [31]:
ordinals_test['Functional'] = ordinals_test['Functional'].replace({'Sal':1,'Sev':2, 'Maj2':3, 'Maj1':4, 'Mod':5, 'Min2':6, 'Min1':7, 'Typ':8})
ordinals_test['Functional'].unique()

array([8, 6, 7, 5, 4, 3], dtype=int64)

In [32]:
ordinals_train['Fence'].unique()

array(['None', 'MnPrv', 'GdPrv', 'GdWo', 'MnWw'], dtype=object)

In [33]:
ordinals_test['Fence'].unique()

array(['None', 'MnPrv', 'GdPrv', 'GdWo', 'MnWw'], dtype=object)

In [34]:
ordinals_train['Fireplace Qu'] = ordinals_train['Fireplace Qu'].replace({'None':1, 'Po':2,'Fa':3,'TA':4, 'Gd':5,'Ex':6})
ordinals_train['Fireplace Qu'].unique()

array([1, 4, 5, 2, 6, 3], dtype=int64)

In [35]:
ordinals_test['Fireplace Qu'] = ordinals_test['Fireplace Qu'].replace({'None':1, 'Po':2,'Fa':3,'TA':4, 'Gd':5,'Ex':6})
ordinals_test['Fireplace Qu'].unique()

array([1, 5, 3, 4, 2, 6], dtype=int64)

In [36]:
ordinals_train['Garage Finish'] = ordinals_train['Garage Finish'].replace({'None':1, 'Unf':2,'RFn':3,'Fin':4})
ordinals_test['Garage Finish'] = ordinals_test['Garage Finish'].replace({'None':1, 'Unf':2,'RFn':3,'Fin':4})

In [37]:
ordinals_train['Garage Qual'] = ordinals_train['Garage Qual'].replace({'None':1, 'Po':2,'Fa':3,'TA':4, 'Gd':5,'Ex':6})
ordinals_train['Garage Qual'].unique()

array([4, 3, 1, 5, 6, 2], dtype=int64)

In [38]:
ordinals_test['Garage Qual'] = ordinals_test['Garage Qual'].replace({'None':1, 'Po':2,'Fa':3,'TA':4, 'Gd':5,'Ex':6})
ordinals_test['Garage Qual'].unique()

array([2, 4, 3, 1, 5], dtype=int64)

In [39]:
ordinals_train['Garage Cond'] = ordinals_train['Garage Cond'].replace({'None':1, 'Po':2,'Fa':3,'TA':4, 'Gd':5,'Ex':6})
ordinals_train['Garage Cond'].unique()

array([4, 3, 1, 2, 5, 6], dtype=int64)

In [40]:
ordinals_test['Garage Cond'] = ordinals_test['Garage Cond'].replace({'None':1, 'Po':2,'Fa':3,'TA':4, 'Gd':5,'Ex':6})
ordinals_test['Garage Cond'].unique()

array([2, 4, 1, 3, 5, 6], dtype=int64)

In [41]:
ordinals_train['Paved Drive'] = ordinals_train['Paved Drive'].replace({'N':1, 'P':2,'Y':3})
ordinals_train['Paved Drive'].unique()

array([3, 1, 2], dtype=int64)

In [42]:
ordinals_test['Paved Drive'] = ordinals_test['Paved Drive'].replace({'N':1, 'P':2,'Y':3})
ordinals_test['Paved Drive'].unique()

array([3, 1, 2], dtype=int64)

In [43]:
ordinals_train['Fence'] = ordinals_train['Fence'].replace({'None':1, 'MnWw':2,'GdWo':3,'MnPrv':4, 'GdPrv':5})
ordinals_test['Fence'] = ordinals_test['Fence'].replace({'None':1, 'MnWw':2,'GdWo':3,'MnPrv':4, 'GdPrv':5})


In [44]:
ordinals_train['Land Slope'] = ordinals_train['Land Slope'].replace({'Sev': 1, 'Mod': 2, 'Gtl': 3})
ordinals_train['Land Slope'].unique()

array([3, 1, 2], dtype=int64)

In [45]:
ordinals_test['Land Slope'] = ordinals_test['Land Slope'].replace({'Sev': 1, 'Mod': 2, 'Gtl': 3})
ordinals_test['Land Slope'].unique()

array([3, 2, 1], dtype=int64)

In [46]:
ordinals_train['Bsmt Exposure'] = ordinals_train['Bsmt Exposure'].replace({'None': 1, 'No': 2, 'Mn': 3, 'Av':4, 'Gd':5})
ordinals_train['Bsmt Exposure'].unique()

array([2, 5, 4, 1, 3], dtype=int64)

In [47]:
ordinals_test['Bsmt Exposure'] = ordinals_test['Bsmt Exposure'].replace({'None': 1, 'No': 2, 'Mn': 3, 'Av':4, 'Gd':5})
ordinals_test['Bsmt Exposure'].unique()

array([2, 4, 1, 3, 5], dtype=int64)

In [48]:
ordinals_train['BsmtFin Type 1'] = ordinals_train['BsmtFin Type 1'].replace({'None': 1, 'Unf': 2, 'LwQ': 3, 'Rec':4, 'BLQ':5, 'ALQ':6, 'GLQ':7})
ordinals_train['BsmtFin Type 1'].unique()                                        

array([7, 2, 6, 4, 1, 5, 3], dtype=int64)

In [49]:
ordinals_test['BsmtFin Type 1'] = ordinals_test['BsmtFin Type 1'].replace({'None': 1, 'Unf': 2, 'LwQ': 3, 'Rec':4, 'BLQ':5, 'ALQ':6, 'GLQ':7})
ordinals_test['BsmtFin Type 1'].unique()   

array([2, 7, 5, 4, 6, 1, 3], dtype=int64)

In [50]:
ordinals_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2051 entries, 0 to 2050
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Lot Shape       2051 non-null   int64
 1   Utilities       2051 non-null   int64
 2   Land Slope      2051 non-null   int64
 3   Overall Qual    2051 non-null   int64
 4   Overall Cond    2051 non-null   int64
 5   Exter Cond      2051 non-null   int64
 6   Bsmt Qual       2051 non-null   int64
 7   Bsmt Cond       2051 non-null   int64
 8   Bsmt Exposure   2051 non-null   int64
 9   BsmtFin Type 1  2051 non-null   int64
 10  Heating QC      2051 non-null   int64
 11  Electrical      2051 non-null   int64
 12  Kitchen Qual    2051 non-null   int64
 13  Functional      2051 non-null   int64
 14  Fireplace Qu    2051 non-null   int64
 15  Garage Finish   2051 non-null   int64
 16  Garage Qual     2051 non-null   int64
 17  Garage Cond     2051 non-null   int64
 18  Paved Drive     2051 non-nul

In [51]:
ordinals_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 878 entries, 0 to 877
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Lot Shape       878 non-null    int64
 1   Utilities       878 non-null    int64
 2   Land Slope      878 non-null    int64
 3   Overall Qual    878 non-null    int64
 4   Overall Cond    878 non-null    int64
 5   Exter Cond      878 non-null    int64
 6   Bsmt Qual       878 non-null    int64
 7   Bsmt Cond       878 non-null    int64
 8   Bsmt Exposure   878 non-null    int64
 9   BsmtFin Type 1  878 non-null    int64
 10  Heating QC      878 non-null    int64
 11  Electrical      878 non-null    int64
 12  Kitchen Qual    878 non-null    int64
 13  Functional      878 non-null    int64
 14  Fireplace Qu    878 non-null    int64
 15  Garage Finish   878 non-null    int64
 16  Garage Qual     878 non-null    int64
 17  Garage Cond     878 non-null    int64
 18  Paved Drive     878 non-null  

In [52]:
# Create Sale price column for train set 
ordinals_train['saleprice'] = ames_train['SalePrice']


In [53]:
ordinals_train.head()

Lot Shape  Utilities  Land Slope  Overall Qual  Overall Cond  Exter Cond  \
0          1          3           3             6             8           3   
1          1          3           3             7             5           3   
2          4          3           3             5             7           4   
3          4          3           3             5             5           3   
4          1          3           3             6             8           3   

   Bsmt Qual  Bsmt Cond  Bsmt Exposure  BsmtFin Type 1  ...  Electrical  \
0          4          4              2               7  ...           5   
1          5          4              2               7  ...           5   
2          4          4              2               7  ...           5   
3          5          4              2               2  ...           5   
4          3          5              2               2  ...           5   

   Kitchen Qual  Functional  Fireplace Qu  Garage Finish  Garage Qual  \
0             3           8             1              3            4   
1             3           8             4              3            4   
2             3           8             1              2            4   
3             2           8             1              4            4   
4             2           8             1              2            4   

   Garage Cond  Paved Drive  Fence  saleprice  
0            4            3      1     130500  
1            4            3      1     220000  
2            4            3      1     109000  
3            4            3      1     174000  
4            4            1      1     138500  

[5 rows x 21 columns]

In [54]:
#curious about the correlations 
ordinals_train.corr()

Lot Shape  Utilities  Land Slope  Overall Qual  Overall Cond  \
Lot Shape        1.000000   0.019472    0.093699     -0.254136      0.058952   
Utilities        0.019472   1.000000   -0.006391      0.030044      0.006142   
Land Slope       0.093699  -0.006391    1.000000      0.035160     -0.000517   
Overall Qual    -0.254136   0.030044    0.035160      1.000000     -0.082770   
Overall Cond     0.058952   0.006142   -0.000517     -0.082770      1.000000   
Exter Cond      -0.006141   0.033331    0.022862      0.020425      0.412351   
Bsmt Qual       -0.233687   0.048990   -0.022325      0.654071     -0.168001   
Bsmt Cond       -0.085655   0.048162    0.004765      0.299712      0.117757   
Bsmt Exposure   -0.189765   0.026428   -0.220292      0.360359     -0.076999   
BsmtFin Type 1  -0.165961  -0.006072   -0.040421      0.291901     -0.008308   
Heating QC      -0.140533   0.015122    0.033377      0.475555      0.002426   
Electrical      -0.120457   0.099063    0.011266      0.266764      0.045973   
Kitchen Qual    -0.208914  -0.006652    0.020611      0.690639     -0.048743   
Functional      -0.019972   0.007649    0.079028      0.181719      0.129261   
Fireplace Qu    -0.202336  -0.014816   -0.061377      0.480804     -0.042856   
Garage Finish   -0.292048   0.001860    0.002423      0.554583     -0.167377   
Garage Qual     -0.141119  -0.008096   -0.003526      0.299361      0.036198   
Garage Cond     -0.132967  -0.007852   -0.001349      0.285909      0.043593   
Paved Drive     -0.168140   0.027739    0.015101      0.323754     -0.013463   
Fence            0.038353   0.014091    0.021877     -0.178032      0.175777   
saleprice       -0.299759   0.026404   -0.057990      0.800207     -0.097019   

                Exter Cond  Bsmt Qual  Bsmt Cond  Bsmt Exposure  \
Lot Shape        -0.006141  -0.233687  -0.085655      -0.189765   
Utilities         0.033331   0.048990   0.048162       0.026428   
Land Slope        0.022862  -0.022325   0.004765      -0.220292   
Overall Qual      0.020425   0.654071   0.299712       0.360359   
Overall Cond      0.412351  -0.168001   0.117757      -0.076999   
Exter Cond        1.000000  -0.004703   0.145130       0.008853   
Bsmt Qual        -0.004703   1.000000   0.631860       0.441008   
Bsmt Cond         0.145130   0.631860   1.000000       0.270348   
Bsmt Exposure     0.008853   0.441008   0.270348       1.000000   
BsmtFin Type 1    0.068104   0.419607   0.315693       0.353698   
Heating QC        0.076155   0.434758   0.194577       0.162924   
Electrical        0.091008   0.271648   0.173951       0.150538   
Kitchen Qual      0.043161   0.526006   0.190923       0.295807   
Functional        0.102688   0.179532   0.203694       0.071763   
Fireplace Qu      0.004793   0.313358   0.129170       0.200572   
Garage Finish    -0.016388   0.487070   0.165863       0.295709   
Garage Qual       0.102809   0.200252   0.141221       0.083395   
Garage Cond       0.106679   0.190853   0.137547       0.067314   
Paved Drive       0.115639   0.310669   0.235832       0.144054   
Fence             0.081397  -0.148322   0.007474      -0.088283   
saleprice         0.036418   0.612188   0.225075       0.424863   

                BsmtFin Type 1  ...  Electrical  Kitchen Qual  Functional  \
Lot Shape            -0.165961  ...   -0.120457     -0.208914   -0.019972   
Utilities            -0.006072  ...    0.099063     -0.006652    0.007649   
Land Slope           -0.040421  ...    0.011266      0.020611    0.079028   
Overall Qual          0.291901  ...    0.266764      0.690639    0.181719   
Overall Cond         -0.008308  ...    0.045973     -0.048743    0.129261   
Exter Cond            0.068104  ...    0.091008      0.043161    0.102688   
Bsmt Qual             0.419607  ...    0.271648      0.526006    0.179532   
Bsmt Cond             0.315693  ...    0.173951      0.190923    0.203694   
Bsmt Exposure         0.353698  ...    0.150538      0.295807    0.071763   
BsmtFin Ty

# Which features have biggest betas?? 

In [55]:
X = ordinals_train.drop(columns='saleprice')
y = ordinals_train['saleprice']

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size = 0.25,
                                                    random_state = 42)

In [57]:
sc = StandardScaler()

In [58]:
Z_train = sc.fit_transform(X_train, y_train)

In [59]:
Z_test = sc.transform(X_test)

In [60]:
lr = LinearRegression()

In [61]:
lr.fit(Z_train, y_train)

LinearRegression()

In [62]:
lr.score(Z_train, y_train)

0.7360050086252594

In [63]:
lr.score(Z_test, y_test)

0.7671115338813521

In [64]:
y_pred = lr.predict(Z_test)
y_pred

array([136699.73474939, 223050.42141944, 277984.03320279, 114422.38765252,
       193771.19899857, 350107.82800307, 205925.25321981, 350107.82800307,
       168904.90557138,  88954.74178465, 131092.84978319, 216642.99150679,
       150414.28935412, 103161.40288237, 128134.11466893,  92705.15969061,
       135910.22124665, 257469.83666372, 249473.0172177 , 210860.03518902,
       247459.58031431, 232966.16964521, 110064.70767946,  88711.31426887,
       156381.8937285 , 287849.05839408, 148399.69138645, 126180.51894713,
       237240.40205763, 115362.26297068, 298053.48541454,  93633.76181707,
       108961.13769752, 205003.84817223, 202247.23696917, 120413.21401144,
       210978.99093119, 248272.96259149, 283585.68451754,  96435.09338859,
       270028.34647198, 160594.18504119, 286086.0414836 , 184425.117122  ,
        85882.6826178 , 166238.81318239, 129699.89691641, 113432.64966911,
       271831.80757592, 138837.08819307, 325604.16098456,  80143.92828561,
       154743.92503658, 1

In [65]:
rmse = mean_squared_error(y_test, y_pred)
rmse**.5

37814.55991245534

In [66]:
lr.coef_

array([-3912.9717179 ,     0.        , -3374.33136207, 33661.31977058,
        -542.6087379 ,  2747.058065  ,  9025.37846388, -8676.42794183,
        7195.58994756,  5086.01572789,  3508.52250389, -1079.02898395,
       15635.07151236, -1027.72726306, 13840.01578972,  3856.23621069,
        7374.95165184, -7449.43914364,   778.73385516,   -39.27091988])

In [67]:
[f'{X.columns[i]}: {lr.coef_[i]}' for i in range(0, len(X.columns))]


['Lot Shape: -3912.9717179008844',
 'Utilities: 0.0',
 'Land Slope: -3374.3313620739727',
 'Overall Qual: 33661.31977057601',
 'Overall Cond: -542.6087378998757',
 'Exter Cond: 2747.058064995226',
 'Bsmt Qual: 9025.378463880543',
 'Bsmt Cond: -8676.427941833008',
 'Bsmt Exposure: 7195.58994756347',
 'BsmtFin Type 1: 5086.015727888967',
 'Heating QC: 3508.522503885359',
 'Electrical: -1079.0289839534216',
 'Kitchen Qual: 15635.071512362058',
 'Functional: -1027.727263060461',
 'Fireplace Qu: 13840.015789716093',
 'Garage Finish: 3856.2362106941728',
 'Garage Qual: 7374.951651835355',
 'Garage Cond: -7449.439143643432',
 'Paved Drive: 778.7338551640469',
 'Fence: -39.270919880657175']

In [68]:
np.median(lr.coef_)

1762.8959600796363

In [69]:
np.std(lr.coef_)

9177.32704690807

In [70]:
np.mean(lr.coef_)

3830.3543714157786

In [71]:
# Create master df that i will use to model 
train_df = ordinals_train
test_df = ordinals_test

In [72]:
train_df

Lot Shape  Utilities  Land Slope  Overall Qual  Overall Cond  \
0             1          3           3             6             8   
1             1          3           3             7             5   
2             4          3           3             5             7   
3             4          3           3             5             5   
4             1          3           3             6             8   
...         ...        ...         ...           ...           ...   
2046          1          3           3             8             5   
2047          1          3           3             4             5   
2048          4          3           3             6             6   
2049          4          3           3             4             5   
2050          4          3           3             7             5   

      Exter Cond  Bsmt Qual  Bsmt Cond  Bsmt Exposure  BsmtFin Type 1  ...  \
0              3          4          4              2               7  ...   
1              3          5          4              2               7  ...   
2              4          4          4              2               7  ...   
3              3          5          4              2               2  ...   
4              3          3          5              2               2  ...   
...          ...        ...        ...            ...             ...  ...   
2046           3          5          4              4               7  ...   
2047           3          4          4              2               5  ...   
2048           3          4          4              2               2  ...   
2049           3          4          4              2               4  ...   
2050           3          4          4              2               2  ...   

      Electrical  Kitchen Qual  Functional  Fireplace Qu  Garage Finish  \
0              5             3           8             1              3   
1              5             3           8             4              3   
2              5             3           8             1              2   
3              5             2           8             1              4   
4              5             2           8             1              2   
...          ...           ...         ...           ...            ...   
2046           5             3           8             5              4   
2047           5             2           8             1              2   
2048           5             2           8             4              2   
2049           5             2           8             5              2   
2050           5             3           8             4              4   

      Garage Qual  Garage Cond  Paved Drive  Fence  saleprice  
0               4            4            3      1     130500  
1               4            4            3      1     220000  
2               4            4            3      1     109000  
3               4            4            3      1     174000  
4               4            4            1      1     138500  
...           ...          ...          ...    ...        ...  
2046            4            4            3      1     298751  
2047            4            4            3      1      82500  
2048            3            3            3      1     177000  
2049            4            4            3      1     144000  
2050            4            4            3      1     189000  

[2051 rows x 21 columns]

In [73]:
test_df

Lot Shape  Utilities  Land Slope  Overall Qual  Overall Cond  Exter Cond  \
0            4          3           3             6             8           2   
1            1          3           3             5             4           3   
2            1          3           3             7             5           3   
3            4          3           3             5             6           3   
4            1          3           3             6             5           3   
..         ...        ...         ...           ...           ...         ...   
873          4          3           3             6             6           3   
874          4          3           3             6             7           4   
875          4          3           3             5             5           3   
876          4          3           3             4             6           3   
877          4          3           3             5             5           4   

     Bsmt Qual  Bsmt Cond  Bsmt Exposure  BsmtFin Type 1  Heating QC  \
0            3          4              2               2           4   
1            5          4              2               2           3   
2            5          5              4               7           5   
3            4          4              2               2           3   
4            5          4              2               5           4   
..         ...        ...            ...             ...         ...   
873          4          4              2               6           3   
874          4          4              2               5           5   
875          4          4              2               5           5   
876          4          4              2               6           3   
877          4          4              2               5           3   

     Electrical  Kitchen Qual  Functional  Fireplace Qu  Garage Finish  \
0             2             2           8             1              2   
1             5             3           8             1              4   
2             5             4           8             5              3   
3             5             3           8             1              2   
4             5             3           8             5              3   
..          ...           ...         ...           ...            ...   
873           5             3           8             4              2   
874           5             4           8             5              3   
875           5             3           8             4              2   
876           5             3           8             1              2   
877           5             3           8             4              2   

     Garage Qual  Garage Cond  Paved Drive  Fence  
0              2            2            3      1  
1              4            4            3      1  
2              4            4            3      1  
3              3            4            1      1  
4              4            4            3      1  
..           ...          ...          ...    ...  
873            4            4            3      1  
874            4            4            3      4  
875            4            4            3      1  
876            4            4            3      3  
877            4            4            3      3  

[878 rows x 20 columns]

In [74]:
# save train and test sets to datasets folder 
train_df.to_csv('./datasets/train_df.csv', index=False)
test_df.to_csv('./datasets/test_df.csv', index=False)